# Generated by Django 3.0.3 on 2020-05-26 18:48

from django.db import migrations, models
import main_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_auto_20200526_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='class_code',
            field=models.CharField(default=main_site.models.create_code, max_length=5),
        ),
    ]
