# Generated by Django 3.0.3 on 2020-05-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_auto_20200526_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='class_datetime',
            new_name='class_date',
        ),
    ]
