# Generated by Django 3.0.3 on 2020-09-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_auto_20200727_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('Terminology', 'Terminology'), ('Techniques', 'Techniques'), ('Poomsae', 'Poomsae'), ('Workouts', 'Workouts'), ('Exercises', 'Exercises'), ('Acrobatics', 'Acrobatics'), ('Extras', 'Extras')], max_length=25),
        ),
    ]
