# Generated by Django 3.0.3 on 2020-09-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0010_auto_20200920_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='NinjaItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
                ('media', models.ImageField(blank=True, upload_to='ninja_items')),
            ],
        ),
    ]
