# Generated by Django 3.0.3 on 2020-09-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0011_ninjaitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninjaitem',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
